name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install fonts and rebuild font cache
        run: |
          sudo apt-get install ttf-mscorefonts-installer
          sudo fc-cache -vfr
          fc-cache -vfr
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          pre_compile: |
            ln -sf /opt/texlive/texdir/texmf-dist/scripts/xindy/xindy.pl /opt/texlive/texdir/bin/x86_64-linuxmusl/xindy
            ln -sf /opt/texlive/texdir/texmf-dist/scripts/xindy/texindy.pl /opt/texlive/texdir/bin/x86_64-linuxmusl/texindy
            wget https://sourceforge.net/projects/xindy/files/xindy-source-components/2.4/xindy-kernel-3.0.tar.gz
            tar xf xindy-kernel-3.0.tar.gz
            cd xindy-kernel-3.0/src
            apk add make
            apk add clisp --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
            make
            cp -f xindy.mem /opt/texlive/texdir/bin/x86_64-linuxmusl/
            cd ../../
          root_file: main.tex
          compiler: arara
          args: " -v "
