name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          pre_compile: |
            ln -sf /opt/texlive/texdir/texmf-dist/scripts/xindy/xindy.pl /opt/texlive/texdir/bin/x86_64-linuxmusl/xindy
            ln -sf /opt/texlive/texdir/texmf-dist/scripts/xindy/texindy.pl /opt/texlive/texdir/bin/x86_64-linuxmusl/texindy
            wget https://sourceforge.net/projects/xindy/files/xindy-source-components/2.4/xindy-kernel-3.0.tar.gz
            tar xf xindy-kernel-3.0.tar.gz
            cd xindy-kernel-3.0/src
            apk add make
            apk add clisp --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
            make
            cp -f xindy.mem /opt/texlive/texdir/bin/x86_64-linuxmusl/
            cd ../../
            apk add msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f
          root_file: main.tex
          compiler: arara
          args: " -v "
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: main.pdf
